# Scraping Twitter with `twint`

`twint` is a Python library for scraping tweets. It can be used either on the command line or in a Python script. For full documentation, I recommend checking out the full wiki for the documentation:https://github.com/twintproject/twint/wiki/

For `twint` variables, see: https://github.com/twintproject/twint/wiki/Configuration

NOTE: You may need to take a break if you're peforming   250 items

In [ ]:
!pip install --upgrade pip

In [ ]:
!pip install nest_asyncio

In [ ]:
!pip3 install twint

In [ ]:
!pip3 install --user --upgrade git+https://github.com/twintproject/twint.git@origin/master#egg=twint

### NOTE
Once you installed and upgraded twint, you may need to restart your kernel. Click on the "Kernel" button in the top menu, and then select "Restart Kernel." Restarting the kernel will still save any installations you've performed (but will clear variables or other commands).

In [1]:
# Import libraries
import nest_asyncio
import twint

In [4]:
nest_asyncio.apply()
# Configure
c = twint.Config()
# Let's look at the tweets of Jorts the Cat
c.Username = "JortsTheCat"
# Let's search for all tweets that contain the string 'paw'
c.Search = "paw"
c.Limit = 10
c.Since = "2022-01-27"
# Save our output as a CSV file
c.Output = "./jorts-paw-tweets.csv"
c.Store_csv = True


# Run
twint.run.Search(c)

1589577998575239168 2022-11-07 06:18:22 -0500 <JortsTheCat> Wow there are smudgy paw prints on your monitor? I‚Äôll keep my eye out for a guy with paws  https://t.co/629Lxb7xwq
1587260619488575488 2022-10-31 21:49:56 -0500 <JortsTheCat> Seasonal reminder: Paw Patrol is copaganda
1585872629403045889 2022-10-28 01:54:33 -0500 <JortsTheCat> If you‚Äôre getting mauled, check if there was a paw print on our app!
1585758728426426368 2022-10-27 18:21:57 -0500 <JortsTheCat> 4 steps (one for each paw)
1568481751810605058 2022-09-10 02:09:25 -0500 <JortsTheCat> @spiderandme @paulbrislen There has to be a space between ‚Äúit‚Äôs not even real‚Äù and ‚Äúoverrated‚Äù and I guess that space is paw paw sized
1568478416944627713 2022-09-10 01:56:10 -0500 <JortsTheCat> Are paw paw fruits real or is that just a joke
1560133959853281280 2022-08-18 01:18:16 -0500 <JortsTheCat> The softest paw can be a claw
1559777375298039809 2022-08-17 01:41:20 -0500 <JortsTheCat> @yugopnik üé∂The softest paw Can be a claw üé∂
1553132265982439424 2022-07-29 17:36:02 -0500 <JortsTheCat> The softest paw can be a claw  https://t.co/e174cFH0rt
1543817625519525888 2022-07-04 00:42:59 -0500 <JortsTheCat> @paramountplus I am worried that paw patrol is unfortunately copaganda
1537939995175989248 2022-06-17 19:27:23 -0500 <JortsTheCat> The softest paw can be a claw. This is still nice guy stuff
1530993243504070656 2022-05-29 15:23:28 -0500 <JortsTheCat> Washed one paw. Resting up to tackle the rest. S√≠ se puede  https://t.co/gvKaUReyh6
1523734412709355521 2022-05-09 14:39:28 -0500 <JortsTheCat> SOFTEST PAW CAN BE A CLAW üî• sign up:  https://t.co/TMLSL0pM2G  https://t.co/dnj648Zkcx
1523217244670496768 2022-05-08 04:24:25 -0500 <JortsTheCat> @skaboomizzy I have been given cat grass but I knocked it over, danced in the soil, and somehow left dirty paw prints on the walls. This has occurred multiple times tbh
1521626430152445953 2022-05-03 19:03:06 -0500 <JortsTheCat> @fidgety_hands This was a wonderful explanation and it made perfect sense (I think?)  Passively assuming good intent isn‚Äôt always ideal, but making a salty joke using a goofy performative assumption of good intent makes it ‚Äòweaponized‚Äô instead of passively letting someone stand on my paw
1519910264916746240 2022-04-29 01:23:40 -0500 <JortsTheCat> @saImineo Yes sometimes the softest paw is a scalpel under anesthesia
1519395819715133441 2022-04-27 15:19:27 -0500 <JortsTheCat> @pizzastevecat What an awesome paw, king
1515146705854877697 2022-04-15 21:54:59 -0500 <JortsTheCat> @Ssidky1 @insidehighered @IndianaGrads Heck yeah! We‚Äôre with you. The softest paw can be a claw ‚ù§Ô∏èüî•
1515130115251863554 2022-04-15 20:49:03 -0500 <JortsTheCat> I was investigating a trash can that had been left ajar. A coworker suggested ‚ÄúJorts, make good choices!‚Äù which startled me somewhat. Mid-spook, I lost my balance and slid down between the can and the wall. As I slid out of sight one paw reached in and shredded the trash bag
1513663713324064768 2022-04-11 19:42:06 -0500 <JortsTheCat> @chhopsky @historerin @Vian1138 @ben_j_lindsay The softest paw can be a claw

## NOTE:
See my above comment: When running multiple twint searches, you may need to pause between them, or restart your kernel.

## Let's look at the dataset we created
We ouput our tweets to a csv file called "jorts-paw-tweets.csv". Let's take a look at it

In [5]:
import pandas as pd

In [6]:
jorts_df = pd.read_csv('jorts-paw-tweets.csv', encoding='utf-8')
jorts_df

,id,conversation_id,created_at,date,time,timezone,user_id,username,name,place,...,geo,source,user_rt_id,user_rt,retweet_id,reply_to,retweet_date,translate,trans_src,trans_dest
0,1589577998575239168,1589577998575239168,2022-11-07 06:18:22 EST,2022-11-07,06:18:22,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
1,1587260619488575488,1587260619488575488,2022-10-31 21:49:56 EDT,2022-10-31,21:49:56,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
2,1585872629403045889,1585872629403045889,2022-10-28 01:54:33 EDT,2022-10-28,01:54:33,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
3,1585758728426426368,1585758728426426368,2022-10-27 18:21:57 EDT,2022-10-27,18:21:57,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
4,1568481751810605058,1568478416944627713,2022-09-10 02:09:25 EDT,2022-09-10,02:09:25,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'spiderandme', 'name': 'Spide...",NaN,NaN,NaN,NaN
5,1568478416944627713,1568478416944627713,2022-09-10 01:56:10 EDT,2022-09-10,01:56:10,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
6,1560133959853281280,1560133959853281280,2022-08-18 01:18:16 EDT,2022-08-18,01:18:16,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
7,1559777375298039809,1559422551545335809,2022-08-17 01:41:20 EDT,2022-08-17,01:41:20,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'yugopnik', 'name': 'Yugopnik...",NaN,NaN,NaN,NaN
8,1553132265982439424,1553132265982439424,2022-07-29 17:36:02 EDT,2022-07-29,17:36:02,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
9,1543817625519525888,1540228232607240192,2022-07-04 00:42:59 EDT,2022-07-04,00:42:59,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'paramountplus', 'name': 'Par...",NaN,NaN,NaN,NaN
10,1537939995175989248,1537939995175989248,2022-06-17 19:27:23 EDT,2022-06-17,19:27:23,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
11,1530993243504070656,1530993243504070656,2022-05-29 15:23:28 EDT,2022-05-29,15:23:28,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
12,1523734412709355521,1523734412709355521,2022-05-09 14:39:28 EDT,2022-05-09,14:39:28,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
13,1523217244670496768,1523201602982531072,2022-05-08 04:24:25 EDT,2022-05-08,04:24:25,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'skaboomizzy', 'name': 'Highw...",NaN,NaN,NaN,NaN
14,1521626430152445953,1521613393047740417,2022-05-03 19:03:06 EDT,2022-05-03,19:03:06,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'fidgety_hands', 'name': 'Fid...",NaN,NaN,NaN,NaN
15,1519910264916746240,1519902361275183104,2022-04-29 01:23:40 EDT,2022-04-29,01:23:40,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'saImineo', 'name': '‚òî sy üåà',...",NaN,NaN,NaN,NaN
16,1519395819715133441,1519383230528507904,2022-04-27 15:19:27 EDT,2022-04-27,15:19:27,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'pizzastevecat', 'name': 'piz...",NaN,NaN,NaN,NaN
17,1515146705854877697,1515141797743321088,2022-04-15 21:54:59 EDT,2022-04-15,21:54:59,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'Ssidky1', 'name': 'Sean Sidk...",NaN,NaN,NaN,NaN
18,1515130115251863554,1515126139701764099,2022-04-15 20:49:03 EDT,2022-04-15,20:49:03,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,[],NaN,NaN,NaN,NaN
19,1513663713324064768,1513328966244786182,2022-04-11 19:42:06 EDT,2022-04-11,19:42:06,-500,1470944601309528072,jortsthecat,Jorts (and Jean),NaN,...,NaN,NaN,NaN,NaN,NaN,"[{'screen_name': 'chhopsky', 'name': 'christin...",NaN,NaN,NaN,NaN